# Generated by Django 2.2b1 on 2019-05-25 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
