# Generated by Django 2.2b1 on 2019-05-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='food',
            field=models.CharField(blank=True, choices=[('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Continental', 'Continental'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='movie',
            field=models.CharField(blank=True, choices=[('Hollywood', 'Hollywood'), ('Bollywood', 'Bollywood'), ('Tollywood', 'Tollywood'), ('Kollywood', 'Kollywood'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='music',
            field=models.CharField(blank=True, choices=[('Classical', 'Classical'), ('Pop', 'Pop'), ('Country', 'Country'), ('Folk', 'Folk'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='sports',
            field=models.CharField(blank=True, choices=[('Cricket', 'Cricket'), ('FootBall', 'FootBall'), ('Tennis', 'Tennis'), ('Kabaddi', 'Kabaddi'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
